name: mozart
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - anyio=2.0.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.4
  - graphite2=1.3.13
  - gstreamer=1.18.2
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - imutils=0.5.3
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyter_server=1.1.3
  - jupyterlab=3.0.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.0
  - libcurl=7.71.1
  - libevent=2.1.10
  - libffi=3.3
  - libglib=2.66.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.0.0
  - libopenblas=0.3.12
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclassic=0.2.5
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.6
  - numpy=1.19.4
  - olefile=0.46
  - opencv=4.5.0
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.3.1
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-opencv=4.5.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.12.9
  - requests=2.25.1
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - autopep8==1.5.4
    - pycodestyle==2.6.0
    - toml==0.10.2
